# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Api Package

on:
  push:
    branches:
      - "master"
      - "ci/deploy-github-actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: resto
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Notify Teams
        if: always()
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "summary": "GitHub Build",
            "themeColor": "0076D7",
            "title": "GitHub Actions Notification",
            "text": "Repo: '"${{ github.repository }}"'\nBranch: '"${{ github.ref_name }}"'\nStatus: '"${{ job.status }}"'"
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

      # todo: variables + urls to secrets !!