# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Api Package

on:
  push:
    branches:
      - "master"
      - "ci/deploy-github-actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: resto
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Init database
        run: |
          mysql -h 127.0.0.1 -u root -proot resto < database/resto_schema.sql
          mysql -h 127.0.0.1 -u root -proot resto < database/resto_data.sql

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DB_URL: jdbc:mysql://127.0.0.1:3306/resto
          DB_USERNAME: root
          DB_PASSWORD: root
        run: |
          mvn -B clean verify \
          sonar:sonar \
          -Dsonar.projectKey=Baromir19_resto-api \
          -Dsonar.organization=baromir19 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.qualitygate.wait=false

      # todo: variables + urls to secrets !!